name: "GitHub Actions Terraform CI/CD"

on:
  pull_request:
  push: { branches: [dev] }

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      working-directory: infrastructure/terafform
    defaults:  
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_ID }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Terraform Setup  
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.6

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.working-directory }}
        

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform apply
        id: apply
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.working-directory }}
