on: 
  workflow_dispatch
defaults:
  run:
    working-directory: infrastructure/terafform
jobs:
  terraform_checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Kubernetes setup
      run: sudo chmod +x kube.sh | kube.sh
     
