name: test
on: 
  workflow_dispatch
defaults:
  run:
    working-directory: infrastructure/terafform
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Kubernetes setup
      run: |
         chmod +x ./kube.sh
         ./kube.sh
      shell: bash
     
