name: manual-terraform-deployment

on: 
  workflow_dispatch
defaults:
  run:
    working-directory: infrastructure/terafform
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: aws cofigure
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - uses: actions/checkout@v2
    - name: Kubernetes setup
      run: |
         chmod +x ./kube.sh
         ./kube.sh
      shell: bash
     
